import type { Article } from "./types";

export const ARTICLES: Article[] = [
  {
    slug: "why-examinees-fail-civil-service-exam",
    title: "Why Examinees Fail the Civil Service Exam: 7 Common Pitfalls & How to Avoid Them",
    seoTitle: "7 Reasons Examinees Fail the CSE",
    category: "Strategy",
    description:
      "A realistic breakdown of the primary reasons examinees fall short on the CSE-PPT—from pacing miscalculations to General Information blind spots.",
    readTimeMinutes: 8,
    publishedDate: "September 2026",
    isoPublishedDate: "2026-09-01T08:00:00+08:00",
    author: "ReviewTayo Editorial Team",
    authorRole: "Civil Service Exam Curriculum Researchers",
    sources: [
      {
        title: "Civil Service Commission Examination Announcement: March 2024 CSE-PPT Results & Statistical Release",
        url: "https://www.csc.gov.ph/csc-releases-results-of-3-march-career-service-exam",
        publisher: "Civil Service Commission (CSC)",
      },
      {
        title: "Republic Act No. 6713 (Code of Conduct and Ethical Standards for Public Officials and Employees)",
        url: "https://www.officialgazette.gov.ph/1989/02/20/republic-act-no-6713/",
        publisher: "Official Gazette of the Republic of the Philippines",
      },
    ],
    keyHighlights: [
      "Poor pacing is one avoidable risk during a long, continuously timed examination.",
      "A balanced review plan should cover every published CSC subtest area.",
      "Full-length timed practice can help candidates rehearse pacing and endurance.",
    ],
    content: [
      "Every year, hundreds of thousands of Filipinos register for the Career Service Examination Pen and Paper Test (CSE-PPT). According to official examination releases by the Civil Service Commission (CSC)—such as the March 2024 Career Service Examination where 57,683 out of 335,385 examinees passed (representing an overall passing rate of 17.20%)—the CSE-PPT maintains a rigorous benchmark where roughly 8 out of 10 candidates do not meet the 80.00% passing threshold.",
      "The CSC release reports the outcome, but it does not identify why individual examinees passed or failed. The seven items below are ReviewTayo editorial recommendations about avoidable pacing and test-day risks; they are not findings attributed to the CSC:",
      "Pitfall 1: Spending 3 to 4 Minutes on a Single Numerical Problem. In the Professional Level, you have 190 minutes to answer 170 items. That leaves you an average of exactly 67 seconds per question. When an examinee gets stubborn with a complex algebraic work problem and burns 4 minutes, they effectively sacrifice three other easy questions at the end of the booklet.",
      "Pitfall 2: Neglecting the General Information Subtest. Many examinees assume General Information is just common knowledge. But RA 6713 norms, specific SALN filing deadlines, and Article III constitutional provisions require precise legal recall. Failing this subtest damages the calibrated general rating.",
      "Pitfall 3: Practicing with Fragmented, Untimed Quizzes. Answering 10 questions casually or solving printed reviewers without time constraints does not build mental stamina. Sitting for over 3 continuous hours without bathroom breaks or smartphone access is an endurance challenge that requires full mock simulations.",
      "Pitfall 4: Relying on Calculators During Study. Calculators are strictly prohibited in the exam hall under CSC Examination Rules. If you develop a habit of typing fractions or percentages into your phone during review, you will freeze when forced to do long division by hand on scratch paper.",
      "Pitfall 5: Misreading Paragraph Organization Items. In Verbal Ability, examinees often pick sentences that sound good in isolation rather than systematically tracing pronoun antecedents and chronological transition markers.",
      "Pitfall 6: Leaving Shading to the Final 5 Minutes. Rushing to shade 170 bubbles in the final minutes leads to misaligned rows, where shading question 141 into row 142 creates an irreversible cascade of errors.",
      "Pitfall 7: Shading Too Lightly or Leaving Smudges. The Optical Mark Reader (OMR) scanners calibrated by the CSC require crisp, dark black ballpen markings. Faint markings or eraser abrasions can cause legitimate correct answers to be marked unread.",
    ],
  },
  {
    slug: "continuous-timer-pacing-strategy",
    title: "The 67-Second Rule: Continuous Timer Pacing Strategy for the 170-Item CSE-PPT",
    seoTitle: "67-Second Rule: CSE Timer Pacing",
    category: "Preparation Tips",
    description:
      "A complete timing guide to managing the 3-hour-10-minute continuous countdown without burning out or running out of time.",
    readTimeMinutes: 7,
    publishedDate: "September 2026",
    isoPublishedDate: "2026-09-05T08:00:00+08:00",
    author: "ReviewTayo Editorial Team",
    authorRole: "Exam Strategy & Pacing Researchers",
    sources: [
      {
        title: "Civil Service Commission Examination Advisory: Test Mechanics & Time Specifications for CSE-PPT",
        url: "https://csc.gov.ph/phocadownload/userupload/erpo/advisories/2024/ExamAdvisory04s2024_School%20Assignmentreminders%202024-0303%20CSE-PPT%20signed.pdf",
        publisher: "Civil Service Commission (CSC)",
      },
    ],
    keyHighlights: [
      "Divide your 190 minutes into four strategic phases with milestone checkpoints.",
      "The 'Two-Pass Strategy': Answer immediate high-confidence items on Pass 1; tackle heavy word problems on Pass 2.",
      "Answer all items: Official CSC examinee instructions do not deduct points for wrong answers, making an educated guess better than leaving a blank.",
    ],
    content: [
      "Unlike modular examinations like the SAT or GRE which divide testing time into partitioned 20-minute sections, the Philippine Civil Service Exam Pen and Paper Test (CSE-PPT) hands you a single 170-item test booklet and starts a single, continuous 3-hour-and-10-minute (190-minute) countdown.",
      "This architecture places the entire burden of pacing and time allocation squarely on your shoulders. Without a disciplined game plan, even well-prepared candidates find themselves with 40 questions left and only 10 minutes remaining on the wall clock.",
      "The Mathematical Reality: 190 minutes divided by 170 questions equals an average of 67.05 seconds per item. Because reading comprehension passages and multi-step word problems realistically require 90 to 120 seconds, our editorial recommendation is to bank time by answering vocabulary, spelling, and constitutional recall questions in 30 seconds or less.",
      "Phase 1 (Minutes 0 to 45) — The Low-Hanging Fruit: Begin by answering General Information (RA 6713, Constitution) and Vocabulary / Grammar items. These questions rely on immediate cognitive recall. If you know the rule, you mark it immediately. This allows you to bank 15 to 20 surplus minutes.",
      "Phase 2 (Minutes 45 to 110) — The Quantitative & Analytical Core: With momentum established, transition to Numerical Ability and Logic Syllogisms. Use your saved buffer to work methodically through multi-step arithmetic, ratios, and percentages.",
      "Phase 3 (Minutes 110 to 160) — Reading Comprehension & Long Passages: Tackle the reading comprehension section while your mental stamina is intact. Skim the questions first before reading the passage to know what details to highlight.",
      "Phase 4 (Minutes 160 to 190) — The Clean-Up & Zero-Blank Check: In the final 30 minutes, revisit flagged items. Most crucially, check your answer sheet for any accidental blanks. Because standard CSC examination guidelines do not impose point deductions for incorrect answers, shading an educated guess on every remaining question gives you an opportunity for credit without risk of penalty.",
    ],
  },
  {
    slug: "professional-vs-subprofessional-difference",
    title: "Professional vs. Subprofessional: Which Civil Service Exam Level Should You Take?",
    seoTitle: "Professional vs Subprofessional CSE",
    category: "Exam Overview",
    description:
      "A comprehensive comparison of eligibility coverage, government salary grades, subtest differences, and career trajectory benefits.",
    readTimeMinutes: 6,
    publishedDate: "September 2026",
    isoPublishedDate: "2026-09-08T08:00:00+08:00",
    author: "ReviewTayo Editorial Team",
    authorRole: "Public Sector Career & Eligibility Researchers",
    sources: [
      {
        title: "1987 Constitution of the Republic of the Philippines — Article IX-B (The Civil Service Commission)",
        url: "https://www.officialgazette.gov.ph/constitutions/1987-constitution/",
        publisher: "Official Gazette of the Republic of the Philippines",
      },
      {
        title: "Civil Service Commission Qualification Standards & Examination Scope Guidelines",
        url: "https://csc.gov.ph/phocadownload/userupload/erpo/announcements/2024/ExamAnnouncement06s2024_Conduct%20of%2011%20Aug%202024%20CSE-PPT.pdf",
        publisher: "Civil Service Commission (CSC)",
      },
    ],
    keyHighlights: [
      "Professional eligibility automatically covers first-level positions, eliminating the need to take both exams.",
      "Analytical Ability is exclusive to Professional; Clerical Ability is exclusive to Subprofessional.",
      "Subprofessional allows 165 items in 2h 40m; Professional requires 170 items in 3h 10m.",
    ],
    content: [
      "One of the most frequent questions from aspiring Philippine civil servants is: 'Should I take the Subprofessional or the Professional level examination first?'",
      "While both examinations grant Career Service Eligibility under the Civil Service Commission, their career utility, salary grade reach, and subtest composition differ significantly.",
      "1. Career Scope and Position Eligibility: The Professional Eligibility confers qualification for both First Level (clerical, administrative, trades, crafts) and Second Level (technical, scientific, executive, and managerial up to Division Chief) positions. In contrast, the Subprofessional Eligibility is strictly limited to First Level clerical positions.",
      "2. The Hierarchy Rule: If you pass the Professional examination, you do NOT need to take the Subprofessional examination. The Professional Certificate of Eligibility supersedes and encompasses Subprofessional eligibility for all clerical job postings across national and local government agencies.",
      "3. Position Levels and Qualification Standards: Under Civil Service Commission qualification standards, government appointments are governed by position level and approved qualification standards manuals rather than salary grade alone. First Level clerical positions (typically spanning Salary Grade 1 up to SG-9) generally require Subprofessional or Professional eligibility. However, permanent appointment to Second Level positions (professional, technical, scientific, and supervisory roles up to Division Chief) requires Career Service Professional eligibility or an appropriate Republic Act No. 1080 professional board license, providing broader career mobility across government agencies.",
      "4. Subtest Comparison: Both levels test Verbal Ability, Numerical Ability, and General Information. However, their third subtest differs: The Professional exam features Analytical Ability (Data interpretation, single-word analogies, logic syllogisms, and identifying assumptions). The Subprofessional exam features Clerical Ability (Alphabetical filing rules, proofreading, spelling, and office procedures).",
      "5. Our Recommendation: If you have completed a 4-year degree or are comfortable with basic deductive logic, our editorial recommendation is to prepare directly for the Professional Level. It provides maximum career mobility without placing an artificial ceiling on your future civil service promotions.",
    ],
  },
  {
    slug: "cse-professional-exam-reviewer-guide",
    title: "Civil Service Exam Professional Reviewer: Comprehensive Breakdown & Preparation Strategy",
    seoTitle: "CSE Professional Reviewer & Guide",
    category: "Exam Overview",
    description:
      "A complete guide to mastering the 170-item CSE-PPT Professional examination: Analytical Ability, continuous 190-minute time budgeting, and subtest weighting.",
    readTimeMinutes: 9,
    publishedDate: "September 2026",
    isoPublishedDate: "2026-09-12T08:00:00+08:00",
    author: "ReviewTayo Editorial Team",
    authorRole: "Civil Service Curriculum Researchers",
    sources: [
      {
        title: "Civil Service Commission Examination Announcement: Conduct of Career Service Examination Pen and Paper Test (CSE-PPT)",
        url: "https://csc.gov.ph/phocadownload/userupload/erpo/announcements/2024/ExamAnnouncement06s2024_Conduct%20of%2011%20Aug%202024%20CSE-PPT.pdf",
        publisher: "Civil Service Commission (CSC)",
      },
      {
        title: "Republic Act No. 6713 (Code of Conduct and Ethical Standards for Public Officials and Employees)",
        url: "https://www.officialgazette.gov.ph/1989/02/20/republic-act-no-6713/",
        publisher: "Official Gazette of the Republic of the Philippines",
      },
    ],
    keyHighlights: [
      "The Professional exam consists of 170 items administered within 3 hours and 10 minutes (190 minutes).",
      "Analytical Ability is unique to the Professional Level and features logic syllogisms, data interpretation, and word associations.",
      "Passing grants eligibility for both First Level (clerical) and Second Level (technical, supervisory) government roles.",
    ],
    content: [
      "The Career Service Examination Professional Level (CSE-PPT Professional) is the flagship eligibility exam conducted by the Philippine Civil Service Commission (CSC). Earning a passing rating of 80.00% or higher confers Career Service Professional Eligibility, granting qualification for permanent appointment to both First-Level (clerical, trades, crafts) and Second-Level (technical, scientific, executive, and managerial up to Division Chief) positions in government agencies, state universities, and government-owned corporations.",
      "1. Structural Blueprint & Allotment: The Professional exam contains 170 multiple-choice items. Unlike modular standardized tests with separate section timers, the CSC provides one single continuous countdown of 3 hours and 10 minutes (190 minutes). This yields an exact mathematical allocation of 67 seconds per item. Managing your pace across 170 items without individual section boundaries is the primary operational test of the exam.",
      "2. The Analytical Ability Subtest: The defining difference between Professional and Subprofessional levels is Analytical Ability. This subtest evaluates deductive reasoning through three primary formats: (a) Logic and Syllogisms, where you determine valid conclusions from categorical premises; (b) Single-word and paired analogies, testing precise semantic relationships; and (c) Data Interpretation, requiring analysis of tables, bar graphs, and charts to answer mathematical and inferential questions.",
      "3. Numerical Ability Scope: The quantitative section tests arithmetic fluency and mathematical logic without the aid of a calculator. Core topics include fraction and decimal conversions, percentage applications (discounts, markups, interest), ratio and proportion, algebraic word problems (age, work, rate-time-distance), and number sequence series. Sharpening handwritten scratchwork and mental arithmetic shortcuts is critical for keeping per-problem time under 90 seconds.",
      "4. Verbal Ability & General Information: Verbal Ability tests English and Filipino grammar, paragraph organization (sequencing sentences into logical narratives), vocabulary in context, and reading comprehension. General Information accounts for approximately 20 items covering Republic Act No. 6713 (Code of Conduct and Ethical Standards for Public Officials and Employees), the 1987 Philippine Constitution (especially Article III Bill of Rights and Article XI Accountability of Public Officers), environmental protection statutes, and human rights basic principles.",
      "5. Review Strategy Recommendation: Our editorial recommendation is to organize preparation around timed simulations. Allocate study time so that high-confidence recall questions (General Information and Vocabulary) are completed quickly, preserving surplus time for multi-step arithmetic and reading passages. Practicing with full-length 170-item simulations helps train mental focus for the uninterrupted 3-hour exam hall experience.",
    ],
  },
  {
    slug: "cse-subprofessional-exam-reviewer-guide",
    title: "Civil Service Exam Subprofessional Reviewer: Subtest Guide & First-Level Eligibility",
    seoTitle: "CSE Subprofessional Reviewer & Guide",
    category: "Exam Overview",
    description:
      "A complete guide to the CSE-PPT Subprofessional Level: 165 items, 160-minute continuous timer, Clerical Ability subtest mastery, and Career Service First-Level positions.",
    readTimeMinutes: 8,
    publishedDate: "September 2026",
    isoPublishedDate: "2026-09-13T08:00:00+08:00",
    author: "ReviewTayo Editorial Team",
    authorRole: "Civil Service Curriculum Researchers",
    sources: [
      {
        title: "Civil Service Commission Examination Announcement: Conduct of Career Service Examination Pen and Paper Test (CSE-PPT)",
        url: "https://csc.gov.ph/phocadownload/userupload/erpo/announcements/2024/ExamAnnouncement06s2024_Conduct%20of%2011%20Aug%202024%20CSE-PPT.pdf",
        publisher: "Civil Service Commission (CSC)",
      },
      {
        title: "Republic Act No. 6713 (Code of Conduct and Ethical Standards for Public Officials and Employees)",
        url: "https://www.officialgazette.gov.ph/1989/02/20/republic-act-no-6713/",
        publisher: "Official Gazette of the Republic of the Philippines",
      },
    ],
    keyHighlights: [
      "The Subprofessional test has 165 items to be answered within 2 hours and 40 minutes (160 minutes).",
      "Clerical Ability replaces Analytical Ability, focusing on alphabetical filing, spelling, and office procedures.",
      "Grants Career Service Subprofessional Eligibility for First-Level government positions (Salary Grades 1 through 9).",
    ],
    content: [
      "The Career Service Examination Subprofessional Level (CSE-PPT Subprofessional) is designed for individuals seeking First-Level eligibility in Philippine government service. A passing mark grants Career Service Subprofessional Eligibility, qualifying passers for permanent appointment to administrative, clerical, custodial, and front-line trade and craft positions across the civil service system.",
      "1. Structural Specifications: The Subprofessional exam consists of 165 multiple-choice questions administered with a continuous time limit of 2 hours and 40 minutes (160 minutes). With 160 minutes for 165 items, examinees have approximately 58.18 seconds per question—a slightly faster pace than the Professional exam's 67 seconds.",
      "2. The Clerical Ability Subtest: In place of Analytical Ability, Subprofessional examinees take the Clerical Ability subtest. This section measures essential office support skills across three distinct question types: (a) Alphabetical Filing and Indexing, requiring strict adherence to standard filing rules (e.g., filing surname first, handling prefixes such as 'De La' or 'San', and indexing organizational titles); (b) Spelling and Proofreading, identifying orthographic errors and punctuation lapses in English and Filipino correspondence; and (c) Basic Office Procedures, testing professional protocol regarding office records handling and official mail routing.",
      "3. Core Subtests (Verbal, Numerical, General Info): Like the Professional test, the Subprofessional exam includes Verbal Ability (vocabulary, grammar, and reading comprehension), Numerical Ability (basic arithmetic, percentages, fractions, and everyday word problems), and General Information (Philippine Constitution, RA 6713 ethical standards, and environmental laws). Math problems in the Subprofessional level generally emphasize fundamental arithmetic and practical calculations rather than advanced algebraic systems.",
      "4. Career Scope & Target Positions: Subprofessional eligibility is ideal for candidates targeting administrative assistant, records clerk, data encoder, bookkeeper, and custodial positions typically falling within Salary Grade 1 (SG-1) to Salary Grade 9 (SG-9). Because the exam does not test advanced logic syllogisms, many candidates find it an accessible entry point into regular public employment.",
      "5. Actionable Review Advice: Focus heavily on alphabetical indexing rules and common spelling pitfalls. In the Clerical Ability subtest, items can often be answered in 20 to 30 seconds, creating valuable buffer time for the numerical problems. Drill with timed question sets to build comfortable speed without second-guessing your clerical sorting sequence.",
    ],
  },
  {
    slug: "how-civil-service-exam-scoring-works",
    title: "How Civil Service Exam Scoring Works: Understanding the 80.00% Passing Benchmark",
    seoTitle: "How Civil Service Exam Scoring Works",
    category: "Strategy",
    description:
      "A factual guide to the CSC 80.00% passing threshold, the unpublished nature of official OMR weighting, and how ReviewTayo provides raw diagnostic scores.",
    readTimeMinutes: 8,
    publishedDate: "September 2026",
    isoPublishedDate: "2026-09-14T08:00:00+08:00",
    author: "ReviewTayo Editorial Team",
    authorRole: "Civil Service Curriculum Researchers",
    sources: [
      {
        title: "Civil Service Commission Examination Announcement: Conduct of Career Service Examination Pen and Paper Test (CSE-PPT)",
        url: "https://csc.gov.ph/phocadownload/userupload/erpo/announcements/2024/ExamAnnouncement06s2024_Conduct%20of%2011%20Aug%202024%20CSE-PPT.pdf",
        publisher: "Civil Service Commission (CSC)",
      },
      {
        title: "Civil Service Commission Official Career Service Results Release & Statistical Overview",
        url: "https://www.csc.gov.ph/csc-releases-results-of-3-march-career-service-exam",
        publisher: "Civil Service Commission (CSC)",
      },
    ],
    keyHighlights: [
      "Official CSC passing threshold requires an overall General Rating of at least 80.00%.",
      "CSC does not publicly disclose whether or how raw correct answers are converted, weighted, or calibrated when calculating the official General Rating.",
      "ReviewTayo provides transparent raw scores and percentage feedback for study pacing, without claiming knowledge of unpublished official CSC formulas.",
    ],
    content: [
      "Every examinee preparing for the Philippine Career Service Examination Pen and Paper Test (CSE-PPT) aims for one primary benchmark: 80.00%. Under Civil Service Commission (CSC) regulations, a candidate must obtain an overall General Rating of at least 80.00% to pass and earn lifetime Career Service Eligibility.",
      "1. The 80.00% General Rating Benchmark: The 80.00% passing requirement is established by official CSC examination announcements. Following the examination, passers and non-passers alike can generate their official Report of Rating through the Online Civil Service Examination Result Generation System (OCSERGS) on the official CSC portal.",
      "2. Unpublished Official Computation Formula: A common misconception among candidates is that an 80.00% rating is simply a basic raw percentage (such as 136 out of 170 items correct). However, the CSC does not publicly disclose whether or how raw correct answers are converted, weighted, or calibrated when calculating the official General Rating. ReviewTayo does not know, simulate, or claim to reproduce any unpublished or proprietary CSC scoring algorithm.",
      "3. Answer Sheet Strategy & Zero Point Deductions: Standard CSC examination guidelines and test instructions direct examinees to answer all items and do not prescribe point deductions for incorrect responses. An omitted bubble guarantees zero credit, whereas an educated guess may earn credit. Therefore, our editorial recommendation is to manage your pacing so you never leave items blank on your answer sheet.",
      "4. How ReviewTayo Diagnostic Scoring Works: During practice on ReviewTayo, your score reports show straightforward, transparent metrics: exact raw counts (e.g., 16/20 correct) and raw percentage performance per subtest. These practice metrics are diagnostic study tools designed to highlight subject weaknesses and pacing bottlenecks; they represent percentage-correct estimates to guide your revision, not official CSC score predictions.",
      "5. Recommended Review Target: Because official examination conditions introduce unique pressures—such as strict continuous time limits, unfamiliar booklet layouts, and exam-hall environments—our editorial recommendation is to target an 85% to 90% raw correct rate during your practice drills. Building a comfortable margin above the 80.00% baseline helps ensure you perform consistently across all subtests on exam day.",
    ],
  },
];
