import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { AlertTriangle, ShieldCheck, Scale, ExternalLink } from "lucide-react";

export const metadata: Metadata = {
  title: "Official Disclaimer",
  description:
    "Official Non-Affiliation and CSC Score Interpretation Notice for ReviewTayo examinees.",
  alternates: {
    canonical: "/disclaimer",
  },
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col bg-slate-50">
      <Header />

      <main className="flex-1 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto space-y-10">
          <div className="text-center space-y-3">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-50 border border-amber-200 text-amber-800 text-xs font-semibold">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
              <span>Public Notice & Non-Affiliation Disclosure</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
              Official Disclaimer
            </h1>
            <p className="text-xs sm:text-sm text-slate-500">
              Clear disclosure of organizational independence and diagnostic score interpretation
            </p>
          </div>

          <div className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-10 shadow-sm space-y-8 text-sm text-slate-700 leading-relaxed">
            {/* Disclaimer 1: Government Non-Affiliation */}
            <section className="space-y-4">
              <div className="flex items-center gap-3 border-b border-slate-100 pb-3">
                <div className="p-2 rounded-xl bg-amber-50 text-amber-700">
                  <Scale className="w-5 h-5" />
                </div>
                <h2 className="text-lg font-bold text-slate-900">
                  1. Non-Affiliation with the Civil Service Commission (CSC)
                </h2>
              </div>
              <p>
                <strong>ReviewTayo</strong> is an independent educational web platform developed solely for academic review and examination preparation.
              </p>
              <div className="p-4 rounded-xl bg-amber-50/70 border border-amber-200 text-amber-950 text-xs sm:text-sm space-y-2">
                <p className="font-semibold">
                  ReviewTayo is NOT affiliated with, associated with, authorized by, endorsed by, or in any way officially connected with:
                </p>
                <ul className="list-disc pl-5 space-y-1 text-xs">
                  <li>The Philippine Civil Service Commission (CSC)</li>
                  <li>The Civil Service Institute (CSI)</li>
                  <li>The Examination, Recruitment, and Placement Office (ERPO)</li>
                  <li>Any Philippine national or local government bureau, agency, or office</li>
                </ul>
              </div>
              <p className="text-xs text-slate-500">
                The official website of the Civil Service Commission can be accessed at{" "}
                <a
                  href="https://www.csc.gov.ph"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-brand-700 underline font-medium inline-flex items-center gap-0.5"
                >
                  www.csc.gov.ph
                  <ExternalLink className="w-3 h-3 ml-0.5" />
                </a>
                . For official exam schedules, application requirements, and room assignments, examinees should always consult the official CSC portal.
              </p>
            </section>

            {/* Disclaimer 2: Score Interpretation */}
            <section className="space-y-4">
              <div className="flex items-center gap-3 border-b border-slate-100 pb-3">
                <div className="p-2 rounded-xl bg-brand-50 text-brand-700">
                  <ShieldCheck className="w-5 h-5" />
                </div>
                <h2 className="text-lg font-bold text-slate-900">
                  2. Diagnostic Score Interpretation Notice
                </h2>
              </div>
              <p>
                Scores generated by our mock exams and practice modules are <strong>diagnostic estimations</strong> based on raw percentages correct against our 80.00% benchmark.
              </p>
              <div className="space-y-2 text-xs text-slate-600 bg-slate-50 p-4 rounded-xl border border-slate-200">
                <p>
                  <strong>Why diagnostic scores differ from official CSC ratings:</strong>
                </p>
                <p>
                  The Civil Service Commission applies a proprietary, calibrated statistical weighting formula across subtests (Verbal, Numerical, Analytical/Clerical, and General Information) that is not publicly disclosed. A practice score of 82% on this platform indicates solid diagnostic mastery of the syllabus material, but does not guarantee an official rating of 82.00% or an official Certificate of Eligibility (CoE) from the Commission.
                </p>
              </div>
            </section>

            {/* Disclaimer 3: Content Authorship */}
            <section className="space-y-3">
              <h2 className="text-base font-bold text-slate-900 border-b border-slate-100 pb-2">
                3. Content Originality & Fair Use Notice
              </h2>
              <p className="text-xs text-slate-600">
                All mock test items on this platform are independently authored educational simulations designed to test competencies defined in the publicly available CSC syllabus. We do not solicit, accept, or publish leaked examination questionnaires. Any resemblance to past examination questions is purely coincidental and inherent to the standardized testing of standard mathematical, grammatical, and Philippine legal principles.
              </p>
            </section>
          </div>

          <div className="text-center pt-2">
            <Link
              href="/"
              prefetch={true}
              className="text-sm font-semibold text-brand-700 hover:text-brand-800 transition"
            >
              &larr; Return to Homepage
            </Link>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
