/**
 * Verified Civil Service Commission (CSC) Examination Data.
 *
 * Sourced strictly from official CSC announcements, advisories, and portals.
 * All factual records retain source URLs, publication references, and
 * Philippine Standard Time (PST) verification timestamps.
 */

import type {
  OfficialSource,
  ExamSession,
  TestingCenter,
  CscRegionalOffice,
  ExamRequirement,
  OfficialAdvisory,
  OfficialLinkItem,
} from "./types";

export const OFFICIAL_SOURCES: OfficialSource[] = [
  {
    id: "src-csc-main",
    publisher: "Civil Service Commission",
    title: "Civil Service Commission Official Website",
    url: "https://www.csc.gov.ph/",
    sourceType: "web-page",
    publishedAt: "2026-09-01",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Official announcements, examination advisories, regional directories, and civil service policies.",
  },
  {
    id: "src-ann-2026-05",
    publisher: "Civil Service Commission",
    title: "Examination Announcement No. 05, s. 2026 — Calendar of Civil Service Examinations through Pen and Paper Test for CY 2027",
    url: "https://www.csc.gov.ph/examination-advisories/examination-announcement-no-05-s-2026-calendar-of-civil-service-examinations-pen-and-paper-test-for-cy-2027",
    sourceType: "exam-announcement",
    publishedAt: "2026-08-25",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Nationwide calendar for 2027 CSE-PPT sessions (14 March 2027 and 8 August 2027), application filing dates, and target examinee targets.",
  },
  {
    id: "src-ann-2026-03",
    publisher: "Civil Service Commission",
    title: "Examination Announcement No. 03, s. 2026 — Conduct of the 9 August 2026 CSE-PPT",
    url: "https://csc.gov.ph/phocadownload/userupload/erpo/announcements/2026/ExamAnn_2026_03_Conduct%20of%2009%20Aug%202026%20CSE-PPT_orig%20signed.pdf",
    sourceType: "exam-announcement",
    publishedAt: "2026-05-15",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Original announcement and primary testing-center localities across 15 CSC Regional Offices.",
  },
  {
    id: "src-ann-2026-04",
    publisher: "Civil Service Commission",
    title: "Examination Announcement No. 04, s. 2026 — Additional and Updated Testing Centers",
    url: "https://csc.gov.ph/phocadownload/userupload/erpo/announcements/2026/ExamAnn_2026_04_Updated%20TCs%20in%20Regions%20VVIIIXNCR%20for%2009%20Aug%202026%20CSE-PPT%20orig%20signed.pdf",
    sourceType: "amendment",
    publishedAt: "2026-07-02",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    supersedesSourceId: "src-ann-2026-03",
    notes: "Official amendments: added Masbate City and Tangub City, transferred Region VIII testing center from Catbalogan to Calbayog City, and removed Caloocan City from NCR.",
  },
  {
    id: "src-ocseas-selector",
    publisher: "Civil Service Commission",
    title: "CSC Online Civil Service Examination Application System (OCSEAS) Region Selector",
    url: "https://ocseas.csc.gov.ph/home",
    sourceType: "application-portal",
    publishedAt: "2026-01-10",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Universal entry point where examinees select their corresponding CSC regional filing system.",
  },
  {
    id: "src-ocseas-roi",
    publisher: "Civil Service Commission",
    title: "Region I OCSEAS Applicant Login",
    url: "https://ocseas.csc.gov.ph/roi/client/login",
    sourceType: "application-portal",
    publishedAt: "2025-11-24",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Official login specifically for CSC Region I applicants. Must not be used for other regions.",
  },
  {
    id: "src-roi-advisory",
    publisher: "Civil Service Commission",
    title: "CSC Region I Examination Application Advisory",
    url: "https://www.csc.gov.ph/regional-offices/region-i/examination/2025-11-24-03-49-14",
    sourceType: "regional-advisory",
    publishedAt: "2025-11-24",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Official filing instructions for Region I examinees utilizing the Region I OCSEAS sub-portal.",
  },
  {
    id: "src-eserve-portal",
    publisher: "Civil Service Commission",
    title: "CSC eServe Online Portal",
    url: "https://services.csc.gov.ph/",
    sourceType: "application-portal",
    publishedAt: "2026-01-15",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Official CSC online portal used by select regions and specific examination sessions.",
  },
  {
    id: "src-ncr-eserve-advisory",
    publisher: "Civil Service Commission",
    title: "CSC NCR Filing Process Advisory for 9 August 2026 CSE-PPT",
    url: "https://csc.gov.ph/regional-offices/ncr/09-august-2026-cse-ppt-filing-process-at-the-csc-ncr-field-offices",
    sourceType: "regional-advisory",
    publishedAt: "2026-05-18",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "NCR field office appointment filing using eServe for the 9 August 2026 session.",
  },
  {
    id: "src-enosa-system",
    publisher: "Civil Service Commission",
    title: "Online Notice of School Assignment (eNOSA v3)",
    url: "https://erpo.csc.gov.ph/eNOSAv3/",
    sourceType: "assignment-system",
    publishedAt: "2026-02-01",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Official nationwide CSC system to verify examinee school and room assignments before exam day.",
  },
  {
    id: "src-ncr-school-assignment",
    publisher: "Civil Service Commission",
    title: "CSC NCR School Assignment Notice Guidelines",
    url: "https://csc.gov.ph/regional-offices/ncr/08-mar-2026-cse-ppt-school-assignment",
    sourceType: "regional-advisory",
    publishedAt: "2026-02-20",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Instructions on matching personal application information when querying eNOSA.",
  },
  {
    id: "src-ncr-suspension",
    publisher: "Civil Service Commission",
    title: "Public Advisory: Suspension of 9 August 2026 CSE-PPT in NCR Testing Centers",
    url: "https://www.csc.gov.ph/regional-offices/ncr/09-august-cse-ppt-cancellation",
    sourceType: "regional-advisory",
    publishedAt: "2026-08-08",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Official emergency suspension due to severe weather and localized flooding across NCR venues.",
  },
  {
    id: "src-career-portal",
    publisher: "Civil Service Commission",
    title: "CSC Careers Portal — Government Job Opportunities",
    url: "https://www.csc.gov.ph/career/",
    sourceType: "job-portal",
    publishedAt: "2026-01-01",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Official database of civil service job vacancies across national and local government agencies.",
  },
  {
    id: "src-exam-announcements-dir",
    publisher: "Civil Service Commission",
    title: "CSC Examination Announcements Directory",
    url: "https://www.csc.gov.ph/downloads/memorandum-circulars/category/560-exam-announcement-2026",
    sourceType: "exam-announcement",
    publishedAt: "2026-01-01",
    retrievedAt: "2026-09-13T10:00:00+08:00",
    officialDomain: true,
    notes: "Official repository of CSC examination memorandum circulars and signed policy advisories.",
  },
];

export const EXAM_SESSIONS: ExamSession[] = [
  {
    id: "session-2027-03-14",
    examId: "cse-ppt-2027-03",
    title: "14 March 2027 CSE-PPT",
    levels: ["professional", "subprofessional"],
    examDate: "14 March 2027",
    applicationOpenAt: "2 November 2026",
    applicationCloseRule: "Continuous until available slots are filled or until otherwise announced by the CSC",
    targetExaminees: 350000,
    targetResultReleaseAt: "11 May 2027",
    status: "upcoming",
    isHistorical: false,
    notes:
      "Testing centers have not yet been announced for this examination. Check back when the CSC releases the specific examination announcement. The calendar announces examination dates but does not confirm testing centers or available regional slots.",
    sourceIds: ["src-ann-2026-05"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "session-2027-08-08",
    examId: "cse-ppt-2027-08",
    title: "8 August 2027 CSE-PPT",
    levels: ["professional", "subprofessional"],
    examDate: "8 August 2027",
    applicationOpenAt: "10 May 2027",
    applicationCloseRule: "Continuous until available slots are filled or until otherwise announced by the CSC",
    targetExaminees: 350000,
    targetResultReleaseAt: "5 October 2027",
    status: "upcoming",
    isHistorical: false,
    notes:
      "Testing centers have not yet been announced for this examination. Check back when the CSC releases the specific examination announcement.",
    sourceIds: ["src-ann-2026-05"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "session-2026-08-09",
    examId: "cse-ppt-2026-08",
    title: "9 August 2026 CSE-PPT",
    levels: ["professional", "subprofessional"],
    examDate: "9 August 2026",
    applicationOpenAt: "12 May 2026",
    applicationCloseAt: "11 June 2026",
    targetExaminees: 350000,
    targetResultReleaseAt: "20 October 2026",
    status: "completed",
    isHistorical: true,
    historicalNote:
      "Historical record. Completed session. Subject to official amendments. Testing centers shown reflect the finalized amended locations.",
    notes:
      "Original announcement superseded in part by Examination Announcement No. 04, s. 2026. NCR testing centers were subsequently suspended on exam day due to weather.",
    sourceIds: ["src-ann-2026-03", "src-ann-2026-04", "src-ncr-suspension"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
];

export const CSC_REGIONAL_OFFICES: CscRegionalOffice[] = [
  {
    code: "region-1",
    name: "Region I (Ilocos Region)",
    shortName: "Region I",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-i",
    contactPageUrl: "https://www.csc.gov.ph/regional-offices/region-i/contact-us",
    applicationPortal: {
      type: "ocseas",
      name: "Region I OCSEAS Applicant Portal",
      url: "https://ocseas.csc.gov.ph/roi/client/login",
      sourceId: "src-ocseas-roi",
      warning: "This login is restricted to CSC Region I applicants only. Examinees in other regions must use the OCSEAS Region Selector.",
    },
    contactDetails: {
      address: "Quezon Avenue, San Fernando City, 2500 La Union",
      telephone: ["(072) 700-5639", "(072) 700-5640"],
      email: ["ro01@csc.gov.ph", "ro01.palad@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-2",
    name: "Region II (Cagayan Valley)",
    shortName: "Region II",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-ii",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Government Center, Carig Sur, Tuguegarao City, 3500 Cagayan",
      telephone: ["(078) 304-1249", "(078) 304-3685"],
      email: ["ro02@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-3",
    name: "Region III (Central Luzon)",
    shortName: "Region III",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-iii",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Diosdado Macapagal Government Center, Maimpis, City of San Fernando, 2000 Pampanga",
      telephone: ["(045) 455-3240", "(045) 455-3241"],
      email: ["ro03@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-4",
    name: "Region IV (CALABARZON & MIMAROPA)",
    shortName: "Region IV",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-iv",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "139 Panay Avenue, Brgy. South Triangle, Diliman, 1103 Quezon City",
      telephone: ["(02) 8927-1830", "(02) 8927-1809"],
      email: ["ro04@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-5",
    name: "Region V (Bicol Region)",
    shortName: "Region V",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-v",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Rawis, Legazpi City, 4500 Albay",
      telephone: ["(052) 482-0699", "(052) 742-0044"],
      email: ["ro05@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-6",
    name: "Region VI (Western Visayas)",
    shortName: "Region VI",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-vi",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "No. 7 Onate Street, Mandurriao, Iloilo City, 5000 Iloilo",
      telephone: ["(033) 321-2668", "(033) 321-2669"],
      email: ["ro06@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-7",
    name: "Region VII (Central Visayas)",
    shortName: "Region VII",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-vii",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Sudlon, Lahug, Cebu City, 6000 Cebu",
      telephone: ["(032) 414-7676", "(032) 414-7488"],
      email: ["ro07@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-8",
    name: "Region VIII (Eastern Visayas)",
    shortName: "Region VIII",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-viii",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Tupaz Government Center, 6500 Tacloban City, Leyte",
      telephone: ["(053) 323-2962", "(053) 323-2857"],
      email: ["ro08@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-9",
    name: "Region IX (Zamboanga Peninsula)",
    shortName: "Region IX",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-ix",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Cabatangan, 7000 Zamboanga City",
      telephone: ["(062) 955-1643", "(062) 955-1644"],
      email: ["ro09@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-10",
    name: "Region X (Northern Mindanao)",
    shortName: "Region X",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-x",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Vamenta Boulevard, Carmen, 9000 Cagayan de Oro City",
      telephone: ["(088) 858-7563", "(088) 858-3905"],
      email: ["ro10@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-11",
    name: "Region XI (Davao Region)",
    shortName: "Region XI",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-xi",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Ecoland Drive, Matina, 8000 Davao City",
      telephone: ["(082) 299-1727", "(082) 299-1728"],
      email: ["ro11@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "region-12",
    name: "Region XII (SOCCSKSARGEN)",
    shortName: "Region XII",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/region-xii",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Government Center, Barangay Carpenter Hill, 9506 Koronadal City",
      telephone: ["(083) 228-9764", "(083) 228-9766"],
      email: ["ro12@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "ncr",
    name: "National Capital Region (NCR)",
    shortName: "NCR",
    officialPageUrl: "https://csc.gov.ph/regional-offices/ncr",
    applicationPortal: {
      type: "eserve",
      name: "CSC eServe / Regional Field Office Instructions",
      url: "https://services.csc.gov.ph/",
      sourceId: "src-ncr-eserve-advisory",
      warning: "CSC NCR utilized eServe for field office appointment booking in recent sessions. Always confirm the specific portal for your target examination.",
    },
    contactDetails: {
      address: "No. 25 Kaliraya Street, Doña Josefa, 1113 Quezon City",
      telephone: ["(02) 8740-0083", "(02) 8740-0085"],
      email: ["roncr@csc.gov.ph", "roncr.pald@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "car",
    name: "Cordillera Administrative Region (CAR)",
    shortName: "CAR",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/car",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "116 Wagner Road, Military Cut-off, 2600 Baguio City",
      telephone: ["(074) 443-5981", "(074) 443-5982"],
      email: ["rocar@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "caraga",
    name: "Caraga Administrative Region (Caraga)",
    shortName: "Caraga",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/caraga",
    applicationPortal: {
      type: "ocseas",
      name: "OCSEAS Region Selector",
      url: "https://ocseas.csc.gov.ph/home",
      sourceId: "src-ocseas-selector",
    },
    contactDetails: {
      address: "Doongan Road, 8600 Butuan City, Agusan del Norte",
      telephone: ["(085) 815-3370", "(085) 815-3371"],
      email: ["rocaraga@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    code: "barmm",
    name: "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)",
    shortName: "BARMM",
    officialPageUrl: "https://www.csc.gov.ph/regional-offices/barmm",
    applicationPortal: {
      type: "in-person",
      name: "Regional Office & Field Filing Advisory",
      url: "https://www.csc.gov.ph/regional-offices/barmm",
      sourceId: "src-csc-main",
      warning: "Follow published BARMM regional advisory for designated filing locations and scheduling.",
    },
    contactDetails: {
      address: "Bangsamoro Government Center, Gov. Gutierrez Avenue, 9600 Cotabato City",
      telephone: ["(064) 421-1243", "(064) 421-1244"],
      email: ["robarmm@csc.gov.ph"],
    },
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
];

export const HISTORICAL_TESTING_CENTERS_AUG_2026: TestingCenter[] = [
  // Region I
  {
    id: "tc-2026-08-reg1-sfc",
    examSessionId: "session-2026-08-09",
    regionCode: "region-1",
    province: "La Union",
    locality: "San Fernando City, La Union",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg1-vigan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-1",
    province: "Ilocos Sur",
    locality: "Vigan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg1-candon",
    examSessionId: "session-2026-08-09",
    regionCode: "region-1",
    province: "Ilocos Sur",
    locality: "Candon City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg1-laoag",
    examSessionId: "session-2026-08-09",
    regionCode: "region-1",
    province: "Ilocos Norte",
    locality: "Laoag City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg1-urdaneta",
    examSessionId: "session-2026-08-09",
    regionCode: "region-1",
    province: "Pangasinan",
    locality: "Urdaneta City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg1-lingayen",
    examSessionId: "session-2026-08-09",
    regionCode: "region-1",
    province: "Pangasinan",
    locality: "Lingayen, Pangasinan",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region II
  {
    id: "tc-2026-08-reg2-tuguegarao",
    examSessionId: "session-2026-08-09",
    regionCode: "region-2",
    province: "Cagayan",
    locality: "Tuguegarao City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg2-cauayan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-2",
    province: "Isabela",
    locality: "Cauayan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg2-bayombong",
    examSessionId: "session-2026-08-09",
    regionCode: "region-2",
    province: "Nueva Vizcaya",
    locality: "Bayombong, Nueva Vizcaya",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg2-diffun",
    examSessionId: "session-2026-08-09",
    regionCode: "region-2",
    province: "Quirino",
    locality: "Diffun, Quirino",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region III
  {
    id: "tc-2026-08-reg3-sfp",
    examSessionId: "session-2026-08-09",
    regionCode: "region-3",
    province: "Pampanga",
    locality: "City of San Fernando, Pampanga",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg3-malolos",
    examSessionId: "session-2026-08-09",
    regionCode: "region-3",
    province: "Bulacan",
    locality: "Malolos City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg3-cabanatuan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-3",
    province: "Nueva Ecija",
    locality: "Cabanatuan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg3-balanga",
    examSessionId: "session-2026-08-09",
    regionCode: "region-3",
    province: "Bataan",
    locality: "Balanga City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg3-baler",
    examSessionId: "session-2026-08-09",
    regionCode: "region-3",
    province: "Aurora",
    locality: "Baler, Aurora",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg3-tarlac",
    examSessionId: "session-2026-08-09",
    regionCode: "region-3",
    province: "Tarlac",
    locality: "Tarlac City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg3-zambales",
    examSessionId: "session-2026-08-09",
    regionCode: "region-3",
    province: "Zambales",
    locality: "Zambales",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region IV
  {
    id: "tc-2026-08-reg4-imus",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Cavite",
    locality: "Imus City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-santacruz",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Laguna",
    locality: "Santa Cruz, Laguna",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-batangas",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Batangas",
    locality: "Batangas City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-morong",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Rizal",
    locality: "Morong, Rizal",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-lucena",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Quezon",
    locality: "Lucena City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-sanjose",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Occidental Mindoro",
    locality: "San Jose, Occidental Mindoro",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-calapan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Oriental Mindoro",
    locality: "Calapan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-boac",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Marinduque",
    locality: "Boac, Marinduque",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-odiongan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Romblon",
    locality: "Odiongan, Romblon",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg4-puerto",
    examSessionId: "session-2026-08-09",
    regionCode: "region-4",
    province: "Palawan",
    locality: "Puerto Princesa City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region V
  {
    id: "tc-2026-08-reg5-legazpi",
    examSessionId: "session-2026-08-09",
    regionCode: "region-5",
    province: "Albay",
    locality: "Legazpi City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg5-daraga",
    examSessionId: "session-2026-08-09",
    regionCode: "region-5",
    province: "Albay",
    locality: "Daraga, Albay",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg5-daet",
    examSessionId: "session-2026-08-09",
    regionCode: "region-5",
    province: "Camarines Norte",
    locality: "Daet, Camarines Norte",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg5-naga",
    examSessionId: "session-2026-08-09",
    regionCode: "region-5",
    province: "Camarines Sur",
    locality: "Naga City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg5-pili",
    examSessionId: "session-2026-08-09",
    regionCode: "region-5",
    province: "Camarines Sur",
    locality: "Pili, Camarines Sur",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg5-sorsogon",
    examSessionId: "session-2026-08-09",
    regionCode: "region-5",
    province: "Sorsogon",
    locality: "Sorsogon City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg5-virac",
    examSessionId: "session-2026-08-09",
    regionCode: "region-5",
    province: "Catanduanes",
    locality: "Virac, Catanduanes",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg5-masbate",
    examSessionId: "session-2026-08-09",
    regionCode: "region-5",
    province: "Masbate",
    locality: "Masbate City",
    levels: ["professional", "subprofessional"],
    status: "added",
    changeNote: "Added by Examination Announcement No. 04, s. 2026",
    sourceIds: ["src-ann-2026-04"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region VI
  {
    id: "tc-2026-08-reg6-iloilo",
    examSessionId: "session-2026-08-09",
    regionCode: "region-6",
    province: "Iloilo",
    locality: "Iloilo City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg6-bacolod",
    examSessionId: "session-2026-08-09",
    regionCode: "region-6",
    province: "Negros Occidental",
    locality: "Bacolod City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg6-roxas",
    examSessionId: "session-2026-08-09",
    regionCode: "region-6",
    province: "Capiz",
    locality: "Roxas City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg6-kalibo",
    examSessionId: "session-2026-08-09",
    regionCode: "region-6",
    province: "Aklan",
    locality: "Kalibo, Aklan",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg6-sanjose",
    examSessionId: "session-2026-08-09",
    regionCode: "region-6",
    province: "Antique",
    locality: "San Jose, Antique",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg6-jordan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-6",
    province: "Guimaras",
    locality: "Jordan, Guimaras",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region VII
  {
    id: "tc-2026-08-reg7-cebu",
    examSessionId: "session-2026-08-09",
    regionCode: "region-7",
    province: "Cebu",
    locality: "Cebu City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg7-lapulapu",
    examSessionId: "session-2026-08-09",
    regionCode: "region-7",
    province: "Cebu",
    locality: "Lapu-Lapu City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg7-dumaguete",
    examSessionId: "session-2026-08-09",
    regionCode: "region-7",
    province: "Negros Oriental",
    locality: "Dumaguete City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg7-bayawan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-7",
    province: "Negros Oriental",
    locality: "Bayawan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg7-tagbilaran",
    examSessionId: "session-2026-08-09",
    regionCode: "region-7",
    province: "Bohol",
    locality: "Tagbilaran City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg7-trinidad",
    examSessionId: "session-2026-08-09",
    regionCode: "region-7",
    province: "Bohol",
    locality: "Trinidad, Bohol",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg7-larena",
    examSessionId: "session-2026-08-09",
    regionCode: "region-7",
    province: "Siquijor",
    locality: "Larena, Siquijor",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region VIII
  {
    id: "tc-2026-08-reg8-tacloban",
    examSessionId: "session-2026-08-09",
    regionCode: "region-8",
    province: "Leyte",
    locality: "Tacloban City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg8-maasin",
    examSessionId: "session-2026-08-09",
    regionCode: "region-8",
    province: "Southern Leyte",
    locality: "Maasin City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg8-calbayog",
    examSessionId: "session-2026-08-09",
    regionCode: "region-8",
    province: "Samar",
    locality: "Calbayog City",
    levels: ["professional", "subprofessional"],
    status: "changed",
    previousLocality: "Catbalogan City",
    changeNote: "Transferred from Catbalogan City by Examination Announcement No. 04, s. 2026",
    replacesTestingCenterId: "tc-2026-08-reg8-catbalogan",
    sourceIds: ["src-ann-2026-04"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg8-catbalogan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-8",
    province: "Samar",
    locality: "Catbalogan City",
    levels: ["professional", "subprofessional"],
    status: "changed",
    changeNote: "Superseded — previously announced, transferred to Calbayog City by Examination Announcement No. 04, s. 2026",
    sourceIds: ["src-ann-2026-03", "src-ann-2026-04"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg8-borongan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-8",
    province: "Eastern Samar",
    locality: "Borongan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg8-catarman",
    examSessionId: "session-2026-08-09",
    regionCode: "region-8",
    province: "Northern Samar",
    locality: "Catarman, Northern Samar",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg8-naval",
    examSessionId: "session-2026-08-09",
    regionCode: "region-8",
    province: "Biliran",
    locality: "Naval, Biliran",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region IX
  {
    id: "tc-2026-08-reg9-zamboanga",
    examSessionId: "session-2026-08-09",
    regionCode: "region-9",
    province: "Zamboanga del Sur",
    locality: "Zamboanga City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg9-pagadian",
    examSessionId: "session-2026-08-09",
    regionCode: "region-9",
    province: "Zamboanga del Sur",
    locality: "Pagadian City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg9-dipolog",
    examSessionId: "session-2026-08-09",
    regionCode: "region-9",
    province: "Zamboanga del Norte",
    locality: "Dipolog City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region X
  {
    id: "tc-2026-08-reg10-cdo",
    examSessionId: "session-2026-08-09",
    regionCode: "region-10",
    province: "Misamis Oriental",
    locality: "Cagayan de Oro City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg10-iligan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-10",
    province: "Lanao del Norte",
    locality: "Iligan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg10-valencia",
    examSessionId: "session-2026-08-09",
    regionCode: "region-10",
    province: "Bukidnon",
    locality: "Valencia City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg10-mambajao",
    examSessionId: "session-2026-08-09",
    regionCode: "region-10",
    province: "Camiguin",
    locality: "Mambajao, Camiguin",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg10-tangub",
    examSessionId: "session-2026-08-09",
    regionCode: "region-10",
    province: "Misamis Occidental",
    locality: "Tangub City",
    levels: ["professional", "subprofessional"],
    status: "added",
    changeNote: "Added by Examination Announcement No. 04, s. 2026",
    sourceIds: ["src-ann-2026-04"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region XI
  {
    id: "tc-2026-08-reg11-davao",
    examSessionId: "session-2026-08-09",
    regionCode: "region-11",
    province: "Davao del Sur",
    locality: "Davao City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg11-digos",
    examSessionId: "session-2026-08-09",
    regionCode: "region-11",
    province: "Davao del Sur",
    locality: "Digos City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg11-tagum",
    examSessionId: "session-2026-08-09",
    regionCode: "region-11",
    province: "Davao del Norte",
    locality: "Tagum City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg11-mati",
    examSessionId: "session-2026-08-09",
    regionCode: "region-11",
    province: "Davao Oriental",
    locality: "Mati City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg11-nabunturan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-11",
    province: "Davao de Oro",
    locality: "Nabunturan, Davao de Oro",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Region XII
  {
    id: "tc-2026-08-reg12-koronadal",
    examSessionId: "session-2026-08-09",
    regionCode: "region-12",
    province: "South Cotabato",
    locality: "Koronadal City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg12-gensan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-12",
    province: "South Cotabato",
    locality: "General Santos City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg12-kidapawan",
    examSessionId: "session-2026-08-09",
    regionCode: "region-12",
    province: "Cotabato",
    locality: "Kidapawan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-reg12-tacurong",
    examSessionId: "session-2026-08-09",
    regionCode: "region-12",
    province: "Sultan Kudarat",
    locality: "Tacurong City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // NCR (National Capital Region)
  {
    id: "tc-2026-08-ncr-qc",
    examSessionId: "session-2026-08-09",
    regionCode: "ncr",
    province: "Metro Manila",
    locality: "Quezon City",
    levels: ["professional", "subprofessional"],
    status: "suspended",
    changeNote: "Suspended on exam day across NCR due to severe weather advisory.",
    sourceIds: ["src-ann-2026-03", "src-ncr-suspension"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-ncr-makati",
    examSessionId: "session-2026-08-09",
    regionCode: "ncr",
    province: "Metro Manila",
    locality: "Makati City",
    levels: ["professional", "subprofessional"],
    status: "suspended",
    changeNote: "Suspended on exam day across NCR due to severe weather advisory.",
    sourceIds: ["src-ann-2026-03", "src-ncr-suspension"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-ncr-pasay",
    examSessionId: "session-2026-08-09",
    regionCode: "ncr",
    province: "Metro Manila",
    locality: "Pasay City",
    levels: ["professional", "subprofessional"],
    status: "suspended",
    changeNote: "Suspended on exam day across NCR due to severe weather advisory.",
    sourceIds: ["src-ann-2026-03", "src-ncr-suspension"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-ncr-taguig",
    examSessionId: "session-2026-08-09",
    regionCode: "ncr",
    province: "Metro Manila",
    locality: "Taguig City",
    levels: ["professional", "subprofessional"],
    status: "suspended",
    changeNote: "Suspended on exam day across NCR due to severe weather advisory.",
    sourceIds: ["src-ann-2026-03", "src-ncr-suspension"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-ncr-manila",
    examSessionId: "session-2026-08-09",
    regionCode: "ncr",
    province: "Metro Manila",
    locality: "Manila",
    levels: ["professional", "subprofessional"],
    status: "suspended",
    changeNote: "Suspended on exam day across NCR due to severe weather advisory.",
    sourceIds: ["src-ann-2026-03", "src-ncr-suspension"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-ncr-caloocan",
    examSessionId: "session-2026-08-09",
    regionCode: "ncr",
    province: "Metro Manila",
    locality: "Caloocan City",
    levels: ["professional", "subprofessional"],
    status: "removed",
    changeNote: "Removed from the testing center list by Examination Announcement No. 04, s. 2026",
    sourceIds: ["src-ann-2026-03", "src-ann-2026-04"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // CAR (Cordillera Administrative Region)
  {
    id: "tc-2026-08-car-baguio",
    examSessionId: "session-2026-08-09",
    regionCode: "car",
    province: "Benguet",
    locality: "Baguio City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-car-latrinidad",
    examSessionId: "session-2026-08-09",
    regionCode: "car",
    province: "Benguet",
    locality: "La Trinidad, Benguet",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-car-bangued",
    examSessionId: "session-2026-08-09",
    regionCode: "car",
    province: "Abra",
    locality: "Bangued, Abra",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-car-tabuk",
    examSessionId: "session-2026-08-09",
    regionCode: "car",
    province: "Kalinga",
    locality: "Tabuk City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-car-bontoc",
    examSessionId: "session-2026-08-09",
    regionCode: "car",
    province: "Mountain Province",
    locality: "Bontoc, Mountain Province",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-car-lamut",
    examSessionId: "session-2026-08-09",
    regionCode: "car",
    province: "Ifugao",
    locality: "Lamut, Ifugao",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-car-luna",
    examSessionId: "session-2026-08-09",
    regionCode: "car",
    province: "Apayao",
    locality: "Luna, Apayao",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },

  // Caraga
  {
    id: "tc-2026-08-caraga-butuan",
    examSessionId: "session-2026-08-09",
    regionCode: "caraga",
    province: "Agusan del Norte",
    locality: "Butuan City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "tc-2026-08-caraga-cabadbaran",
    examSessionId: "session-2026-08-09",
    regionCode: "caraga",
    province: "Agusan del Norte",
    locality: "Cabadbaran City",
    levels: ["professional", "subprofessional"],
    status: "completed",
    sourceIds: ["src-ann-2026-03"],
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
];

export const OFFICIAL_ADVISORIES: OfficialAdvisory[] = [
  {
    id: "adv-ncr-suspension-2026",
    examSessionId: "session-2026-08-09",
    type: "suspension",
    title: "Urgent: Weather Suspension for 9 August 2026 CSE-PPT in All NCR Testing Centers",
    summary:
      "The Civil Service Commission officially suspended the conduct of the 9 August 2026 CSE-PPT across all National Capital Region testing centers due to heavy southwest monsoon rains and flooding. Affected examinees were rescheduled per separate CSC advisory.",
    affectedRegionCodes: ["ncr"],
    affectedTestingCenterIds: [
      "tc-2026-08-ncr-qc",
      "tc-2026-08-ncr-makati",
      "tc-2026-08-ncr-pasay",
      "tc-2026-08-ncr-taguig",
      "tc-2026-08-ncr-manila",
    ],
    publishedAt: "2026-08-08",
    sourceId: "src-ncr-suspension",
    priority: "urgent",
    active: true,
  },
  {
    id: "adv-ann-04-amendment",
    examSessionId: "session-2026-08-09",
    type: "testing-center-amendment",
    title: "Official Amendment: Additional & Updated Testing Centers (Announcement No. 04, s. 2026)",
    summary:
      "Official updates: Added Masbate City (Region V) and Tangub City (Region X). Transferred Region VIII testing center from Catbalogan City to Calbayog City. Removed Caloocan City from the NCR testing center list.",
    affectedRegionCodes: ["region-5", "region-8", "region-10", "ncr"],
    affectedTestingCenterIds: [
      "tc-2026-08-reg5-masbate",
      "tc-2026-08-reg8-calbayog",
      "tc-2026-08-reg8-catbalogan",
      "tc-2026-08-reg10-tangub",
      "tc-2026-08-ncr-caloocan",
    ],
    publishedAt: "2026-07-02",
    sourceId: "src-ann-2026-04",
    priority: "important",
    active: true,
  },
  {
    id: "adv-cal-2027-notice",
    examSessionId: "session-2027-03-14",
    type: "general",
    title: "Official Calendar Announcement: 2027 CSE-PPT Schedule Confirmed",
    summary:
      "CSC Examination Announcement No. 05, s. 2026 published the nationwide calendar for 2027 pen-and-paper examinations. The first 2027 session takes place on 14 March 2027 with filing opening on 2 November 2026.",
    affectedRegionCodes: [],
    affectedTestingCenterIds: [],
    publishedAt: "2026-08-25",
    sourceId: "src-ann-2026-05",
    priority: "normal",
    active: true,
  },
];

export const OFFICIAL_LINKS_DIRECTORY: OfficialLinkItem[] = [
  // General
  {
    id: "link-csc-home",
    label: "Visit the Official CSC Website",
    category: "general",
    url: "https://www.csc.gov.ph/",
    domainBadge: "csc.gov.ph",
    description: "Official announcements, examination advisories, regional-office directories, and civil service guidelines.",
    sourceId: "src-csc-main",
  },
  {
    id: "link-csc-announcements",
    label: "View Official Examination Announcements",
    category: "general",
    url: "https://www.csc.gov.ph/downloads/memorandum-circulars/category/560-exam-announcement-2026",
    domainBadge: "csc.gov.ph",
    description: "Download signed copies of official examination announcements, amendments, and policy guidelines.",
    sourceId: "src-exam-announcements-dir",
  },

  // Application Portals
  {
    id: "link-ocseas-selector",
    label: "Select Your Region in CSC OCSEAS",
    category: "application",
    url: "https://ocseas.csc.gov.ph/home",
    domainBadge: "ocseas.csc.gov.ph",
    description: "Official region-selection entry point for the CSC Online Civil Service Examination Application System.",
    sourceId: "src-ocseas-selector",
    isLogin: true,
  },
  {
    id: "link-ocseas-roi",
    label: "Region I OCSEAS Applicant Login",
    category: "application",
    url: "https://ocseas.csc.gov.ph/roi/client/login",
    domainBadge: "ocseas.csc.gov.ph",
    regionScope: "Region I Only",
    description: "Dedicated applicant portal for CSC Region I. Only use this link if applying under Region I instructions.",
    warning: "Restricted to Region I applicants. Other regions will fail authentication here; use the OCSEAS Region Selector instead.",
    sourceId: "src-ocseas-roi",
    isLogin: true,
  },
  {
    id: "link-csc-eserve",
    label: "Open CSC eServe Portal",
    category: "application",
    url: "https://services.csc.gov.ph/",
    domainBadge: "services.csc.gov.ph",
    description: "Official online appointment service utilized by select CSC regional field offices (such as CSC NCR) for personal appearance schedules.",
    warning: "Check your CSC Regional Office advisory to confirm if eServe is designated for your session.",
    sourceId: "src-eserve-portal",
    isLogin: true,
  },

  // School and Room Assignment
  {
    id: "link-enosa-system",
    label: "Check Your School Assignment (eNOSA)",
    category: "assignment",
    url: "https://erpo.csc.gov.ph/eNOSAv3/",
    domainBadge: "erpo.csc.gov.ph",
    description: "Official Online Notice of School Assignment system. Check your testing venue, building, and assigned room number.",
    warning: "School assignments are typically uploaded 1 to 2 weeks before exam day. Enter your exact application details.",
    sourceId: "src-enosa-system",
  },

  // Government Careers
  {
    id: "link-csc-careers",
    label: "Browse Government Job Opportunities",
    category: "careers",
    url: "https://www.csc.gov.ph/career/",
    domainBadge: "csc.gov.ph",
    description: "Explore vacant government positions nationwide submitted by participating agencies to the CSC Job Portal.",
    sourceId: "src-career-portal",
  },
];

export const EXAM_REQUIREMENTS_DATA: ExamRequirement[] = [
  {
    id: "req-app-form",
    examSessionId: "session-2027-03-14",
    category: "application-form",
    title: "Accomplished CS Form No. 100",
    description: "Duly accomplished Application Form (CS Form No. 100, revised series). Do not sign the application form yet; signature and thumbprint must be executed in the presence of the CSC receiving officer.",
    required: true,
    sourceId: "src-ann-2026-05",
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "req-photos",
    examSessionId: "session-2027-03-14",
    category: "photograph",
    title: "Four (4) Identical Passport-Size Photos",
    description: "Standard passport size (4.5 cm x 3.5 cm) on clean white background, taken within three (3) months. Must include full handwritten name tag (First Name, Middle Initial, Last Name, and Extension) and signature over printed name.",
    required: true,
    sourceId: "src-ann-2026-05",
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "req-valid-id",
    examSessionId: "session-2027-03-14",
    category: "identification",
    title: "Original & Photocopy of Valid ID",
    description: "Must be a valid government-issued ID containing the applicant's clear photo, date of birth, and signature (e.g. PhilID / ePhilID, Passport, Driver's License, SSS/GSIS UMID, PRC ID, Voter's ID, Postal ID).",
    required: true,
    sourceId: "src-ann-2026-05",
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "req-fee",
    examSessionId: "session-2027-03-14",
    category: "fee",
    title: "Examination Fee of ₱500.00",
    description: "The nationwide standard examination fee is Five Hundred Pesos (₱500.00). Paid directly to the designated CSC cashier or authorized online payment partner.",
    required: true,
    sourceId: "src-ann-2026-05",
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "req-age",
    examSessionId: "session-2027-03-14",
    category: "eligibility",
    title: "Age Requirement (At Least 18 Years Old)",
    description: "Must be at least 18 years of age on the date of filing the application.",
    required: true,
    sourceId: "src-ann-2026-05",
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "req-citizenship",
    examSessionId: "session-2027-03-14",
    category: "eligibility",
    title: "Filipino Citizenship",
    description: "Must be a Filipino citizen of good moral character, without any conviction by final judgment of an offense involving moral turpitude, dishonorable discharge, or dismissal for cause from government service.",
    required: true,
    sourceId: "src-ann-2026-05",
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "req-frequency",
    examSessionId: "session-2027-03-14",
    category: "eligibility",
    title: "Three-Month Rule (Examination Frequency)",
    description: "Examinees must not have taken the same level of Career Service Examination (Professional or Subprofessional) within three (3) months prior to the date of examination.",
    required: true,
    sourceId: "src-ann-2026-05",
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
  {
    id: "req-personal-appearance",
    examSessionId: "session-2027-03-14",
    category: "personal-appearance",
    title: "Personal Appearance",
    description: "Personal appearance is strictly required during filing for biometric verification, thumbmark, and signature capture.",
    required: true,
    sourceId: "src-ann-2026-05",
    lastVerifiedAt: "13 September 2026, 10:00 AM PST",
  },
];

export const APPLICATION_STEPS = [
  {
    step: 1,
    title: "Choose Examination Date & Level",
    description: "Decide between the Professional (170 items, 3h10m) or Subprofessional (165 items, 2h40m) level based on your educational qualifications and career goals.",
  },
  {
    step: 2,
    title: "Read the Specific CSC Announcement",
    description: "Download and read the signed official examination announcement from the CSC website for complete guidelines, regional allotments, and rules.",
  },
  {
    step: 3,
    title: "Identify Your CSC Regional Office",
    description: "Choose the CSC region where you will physically file and sit for the exam. Application policies, slots, and appointment schedules are managed regionally.",
  },
  {
    step: 4,
    title: "Access the Designated Portal",
    description: "Navigate to the portal specified by your region (e.g. OCSEAS Region Selector or eServe). Do not use another region's sub-portal.",
  },
  {
    step: 5,
    title: "Register or Log In to CSC Account",
    description: "Create or access your verified account on the official csc.gov.ph domain. Keep your account credentials safe.",
  },
  {
    step: 6,
    title: "Fill Out Required Application Information",
    description: "Enter your personal profile, educational background, and contact details matching your government IDs exactly.",
  },
  {
    step: 7,
    title: "Select an Available Testing Center & Slot",
    description: "Select an announced testing-center locality and available appointment schedule. Slots are first-come, first-served and may close early.",
  },
  {
    step: 8,
    title: "Prepare Required Documents & Photos",
    description: "Complete CS Form 100, four passport photos with name tag and signature, valid government ID original and photocopy, and ₱500 fee.",
  },
  {
    step: 9,
    title: "Personal Appearance & Verification",
    description: "Appear in person at the designated CSC Regional or Field Office on your appointment date for biometric logging, thumbprint, and receipt.",
  },
  {
    step: 10,
    title: "Safeguard Your Application Receipt",
    description: "Keep your official receipt (OR) and application confirmation stub in a secure location. You must present this on examination day.",
  },
  {
    step: 11,
    title: "Verify School Assignment on eNOSA",
    description: "Approximately 1 to 2 weeks before the exam, visit the CSC eNOSA system to look up your assigned school, building, and room number.",
  },
  {
    step: 12,
    title: "Review Final Exam Day Advisories",
    description: "Check the CSC website 2 to 3 days before exam day for any weather alerts, room reassignment notices, or gate instructions.",
  },
];

export const EXAM_DAY_CHECKLIST = {
  beforeLeaving: [
    { text: "Confirm your assigned testing school, building, and room on official eNOSA v3.", source: "src-enosa-system" },
    { text: "Check your CSC Regional Office website and Facebook page for suspension, flood, or transfer advisories.", source: "src-csc-main" },
    { text: "Plan travel route in advance. Gates strictly close at 7:45 AM nationwide with zero exceptions.", source: "src-ann-2026-03" },
    { text: "Wear proper examination dress code: plain casual attire with sleeves (collared shirt or t-shirt) and closed shoes. Shorts, sleeveless tops, and slippers are prohibited.", source: "src-ann-2026-03" },
  ],
  bringItems: [
    { text: "Original valid government-issued ID (same ID presented during filing, with photo, birthdate, and signature).", source: "src-ann-2026-03" },
    { text: "Official Application Receipt / Notice of School Assignment printout.", source: "src-ann-2026-03" },
    { text: "Black ballpens only (bring 2 to 3 pens). Gel pens, sign pens, friction/erasable pens, and pencils are strictly prohibited on answer sheets.", source: "src-ann-2026-03" },
    { text: "Clear, transparent drinking water bottle and light snacks (labels removed if required).", source: "src-ann-2026-03" },
  ],
  prohibitedItems: [
    { text: "Calculators of any type (scientific, basic, financial).", source: "src-ann-2026-03" },
    { text: "Cellular phones, tablets, smart glasses, Bluetooth earphones, and portable electronics.", source: "src-ann-2026-03" },
    { text: "Smartwatches, digital watches with calculator/camera, and programmable timepieces (only simple analog watches allowed).", source: "src-ann-2026-03" },
    { text: "Books, reviewer notes, crib notes, blank paper, and scratch papers (scratch work must be done on the test booklet margins).", source: "src-ann-2026-03" },
    { text: "Firearms, sharp objects, and weapons.", source: "src-ann-2026-03" },
  ],
  venueProtocols: [
    { text: "Be at the school gate by 6:00 AM to locate your assigned building and room.", source: "src-ann-2026-03" },
    { text: "Strict gate closure at 7:45 AM. Examinees arriving at 7:46 AM or later are barred from entering.", source: "src-ann-2026-03" },
    { text: "Listen attentively to the room examiner's preliminary briefing, answer-sheet filling instructions, and timing cues.", source: "src-ann-2026-03" },
    { text: "Continuous timer: The exam operates on a single continuous time allotment (190 mins Professional / 160 mins Subprofessional). No per-subtest timeouts.", source: "src-ann-2026-03" },
  ],
};

/**
 * Verified Next Upcoming CSE-PPT Session
 * Source: CSC Examination Announcement No. 05, s. 2026
 */
export const NEXT_UPCOMING_EXAM_DATE = "2027-03-14";
export const NEXT_UPCOMING_EXAM_LABEL = "March 14, 2027";
export const NEXT_UPCOMING_EXAM_NAME = "March 2027 CSE-PPT";

